---
title: "Evaluating bee habitat provisioning within agricultural landscapes"
author: "Morgan Mackert"
date: "December 13, 2016"
output: word_document
---

```{r load packages, echo = FALSE}
library(lubridate)
library(ggplot2)
```

Load bee and plant data.
```{r load data, echo = FALSE}
setwd("C:/Users/Morgan/Documents/ISU/Semester 3/R/mmackert/Data")
simplebees <- read.csv("bees/working/simplebees.csv", header =T)
simplebees$Date <- mdy(simplebees$Date)
head(simplebees)

simpleplants <- read.csv("plants/working/simpleplants.csv", header = T)
simpleplants$Date <- mdy(simpleplants$Date)
head(simpleplants)

TotalsByPeriod <- read.csv("~/ISU/Semester 3/R/mmackert/Data/TotalsByPeriod.csv")
```

Plot the number of bee specimens and the number of plant species by date, and include best fit line.
```{r bees and plants by date}
setwd("C:/Users/Morgan/Documents/ISU/Semester 3/R/mmackert/Data")
with(simplebees, plot(TotalBees ~ Date, ylab = "Bee Abundance"));
with(simplebees, abline(lm(TotalBees ~ Date)))
with(simpleplants, plot(TotalPlants ~ Date, ylab = "Flowering Plant Richness"));
with(simpleplants, abline(lm(TotalPlants ~ Date)))
```

Plot the number of bee specimens and the number of plant species by site.
```{r bees and plants by site}
with(simplebees, plot(TotalBees ~ Site, ylab = "Bee Abundance"))
with(simpleplants, plot (TotalPlants ~ Site, ylab = "Number of Bee Species"))
```

Now do it with ggplot.
```{r bees and plants by date ggplot}
beesbysiteplot <- ggplot(simplebees, aes(x = Date, y = TotalBees)) + 
  geom_point(shape = 19, size = 2) + 
  geom_smooth(method = lm) +
  ggtitle("Bee Abundance") +
  theme(plot.title = element_text(size = 20, face = "bold", margin = margin(10, 0, 10, 0))) +
  labs(x = "Date", y = "Number of Individuals")
beesbysiteplot

plantsbysiteplot <- ggplot(simpleplants, aes(x = Date, y = TotalPlants)) +
  geom_point(shape = 19, size = 2) +
  geom_smooth(method = lm)+
  ggtitle("Plant Richness") +
  theme(plot.title = element_text(size = 20, face = "bold", margin = margin(10, 0, 10, 0))) +
  labs(x = "Date", y = "Number of Species")
plantsbysiteplot
```

Color code the lines by site.
```{r bees and plants by date ggplot with color coded lines}
beesbysiteplotcolorline <- ggplot(simplebees, aes(x = Date, y = TotalBees, color = Site)) + 
  geom_point(shape = 19, size = 2) +
  geom_line() +
  ggtitle("Bee Abundance") +
  theme(plot.title = element_text(size = 20, face = "bold", margin = margin(10, 0, 10, 0))) +
  labs(x = "Date", y = "Number of Individuals")
beesbysiteplotcolorline

plantsbysiteplotcolorline <- ggplot(simpleplants, aes(x = Date, y = TotalPlants, color = Site)) +
  geom_point(shape = 19, size = 2) +
  geom_line() +
  ggtitle("Plant Richness") +
  theme(plot.title = element_text(size = 20, face = "bold", margin = margin(10, 0, 10, 0))) +
  labs(x = "Date", y = "Number of Species")
plantsbysiteplotcolorline
```

Plot bee abundance versus blooming forb richness by sample period.
```{r bees vs plants by period}
TotalsByPeriodplot <- ggplot(TotalsByPeriod, aes(x = SPPlants, y = SPBees, color = (SamplePeriod))) +
  geom_point(shape = 19, size = 3) +
  geom_line() +
  geom_abline() +
  ggtitle("Bee Abundance vs. Flowering Plant Richness\nby Sample Period") +
  labs(x = "Flowering Plant Species Richness", y = "Bee Abundance") +
  theme(legend.title = element_text(color = "black", size = 12, face = NULL)) + 
  scale_color_discrete(name = "Sample Period", breaks = c("EarlyMay", "LateMay", "June", "July", "August")) +
  theme_bw()
TotalsByPeriodplot
```


